### ISSUE TITLE
volume_label: and local_base_path: ???

### ISSUE THREAD

**Issue by cyberpunkbln** [lilopkins/lnk-rs#10]
Hello,

now i have a solution for plain lnks that i have made with windows without giving an extra icon and let windows take the icon from the exe without setting icon_location.

Cool, but i don't find the path of the exe that is linked in the lnk?
I see that an output from ShellLink has volume_label and local_base_path but i became access to this variables? Are in LinkInfo but not method give LinkInfo back??? relative_path is not usefull.

thx for answer so an cheap questions.

**Comment by lilopkins** [comment]
Hi. This should be fixed with `lnk = "0.5.1"`.

You should be able to get the information you need now:
```rust
let shortcut = ShellLink::open(unimplemented!()).unwrap();
let link_info = shortcut.link_info().unwrap();
// now you'll have access to volume_id().unwrap().volume_label() and local_base_path()
```
More documentation on the new methods of LinkInfo can be found on [docs.rs](https://docs.rs/lnk/0.5.1/lnk/linkinfo/struct.LinkInfo.html).

I'm going to close this issue for now, but if this doesn't solve your problem, please re-open it!
